version: "3.3"
services:

  redis:
    image: redis:alpine
    networks:
      - proxy

  php:
    build:
      context: .
      dockerfile: phpdocker/php-fpm/Dockerfile
    image: bcio-phpfpm:7.3-rev0
    working_dir: /application
    networks:
      - proxy
    dns: 172.20.10.250
    volumes:
      - ..:/application/www:cached
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      - ./phpdocker/php-fpm/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
    links:
      - redis
    external_links:
      - "tribe-mysql:mysql"
      - "tribe-mail:mail"

  webserver:
    image: nginx:stable-alpine
    working_dir: /application
    environment:
      - VIRTUAL_HOST=bcio.tribe,*.bcio.tribe
    volumes:
      - ..:/application/www:cached
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./phpdocker/nginx/fastcgi.conf:/etc/nginx/fastcgi_params
    networks:
      - proxy
    links:
      - php

networks:
  proxy:
    external:
      name: global_proxy


